#!/bin/sh


weatherreport="/tmp/weatherreport"
getforecast() { curl -4 -sf "wttr.in/compostela" > "$weatherreport" || exit 1 ;}

showweather() { printf "%s" "$(sed '16q;d' "$weatherreport" |
	grep -wo "[0-9]*%" | sort -rn | sed "s/^/🌧️/g;1q" | tr -d '\n')"
sed '13q;d' "$weatherreport" | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " 🥶" $1 "°","🌞" $2 "°"}' ;}

case $BLOCK_BUTTON in
	1) setsid -f st -e less -SsR~ "$weatherreport" ;;
	3) st -e $HOME/.config/barblocks/luna ;;
	6) st -e vim "$0" ;;
esac

[ "$(stat -c %y "$weatherreport" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] ||
	getforecast

showweather
