#!/bin/sh
case $BLOCK_BUTTON in
	1) notify-send "$(curl -4sf ipinfo.io | tr -d '{"}' || curl -4sf ifconfig.co/json)";;
	3) wireshark;;
esac

[ -z $(pidof dwm) ] && curl -4sf ipinfo.io | tr -d '"' || printf "📡"
