#!/bin/sh

case $BLOCK_BUTTON in
	3) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	1) setsid -f st -e htop ;;
esac

printf "%s" "🧠 $(free -h | awk '/Mem/ {print $3"/"$2}')"
