#!/bin/sh

a=$(/usr/bin/lsblk -pnl | fzf --cycle --reverse | awk '{print $7, $1}')
#b=$(/usr/bin/lsblk -pnl | fzf | awk '{print $1}')
#echo $a
b=$(printf "$a\\n" | awk '{print $2}')
case $b in
	"") sudo mount $a /mnt && notify-send "unidad $a montada";;
	*) sudo umount $b && notify-send "$b unidad desmontada";;
esac

