#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f st -e alsamixer;;
	3) $HOME/scripts/cmusa;;
esac

vol=$(amixer sget Master | awk '/%/ {print $4}' | tr -d '[%]')

[ "$(amixer sget Master | awk '/%/ {print $6}' | tr -d '[]')" = "off" ] && echo " 🔇" && exit

if [ "$vol" -gt 70 ]; then
	echo " 🔊 $vol%"
elif [ "$vol" -gt 35 ]; then
	echo "🔉 $vol%"
else
	echo "🔈 $vol%"
fi
