#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

fondo.sh aleatorio & # fijo o aleatorio
#compton & # distractive
redshift &
dunst &
setxkbmap es -option caps:escape &
xrdb ~/.config/x11/xresources &
$HOME/descargas/build/xbanish-master/xbanish &
# aumenta velocidad de scrolling
xset r rate 300 50 &

while :; do
	grep dwm ~/.local/share/desktop && dwmblocks &
	$(cat ~/.local/share/desktop)
done
