#! /bin/sh

#source ~/.profile
pidof sxhkd || sxhkd &
compton & #; pidof bspwm && $HOME/.config/polybar/launch &
fondo_escritorio.sh aleatorio &

#xidle -delay 3600 -area 768 -program "sudo poweroff" &
setxkbmap es -option caps:escape &
#xmodmap -e "keycode 66 = Shift_L" &
#xmodmap -e "remove Lock = Caps_Lock" -e "keycode 66 = Escape" &

pidof redshift || redshift &
#pywall -R &
#setxkbmap -option caps:none
pidof polybar || $HOME/.config/polybar/launch.sh &
#$HOME/scripts/vol2 

pidof dunst || $HOME/descargas/build/dunst/dunst &
#( sleep 2s && bash /usr/local/bin/lemonbar.sh | lemonbar -p -F#FFFFFFFF -B#FF222222 -f "mononoki Nerd Font"-8 -f FontAwesome-8) &
#panel $
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d IV V VI VII 
xsetroot -cursor_name left_ptr &
#aumenta velocidad de scrolling
xset r rate 300 50 &
#bspc rule -a 'Pcmanfm' desktop='^2' follow=off
pidof xbanish || $HOME/descargas/build/xbanish-master/xbanish &
pidof xob || $HOME/.local/bin/nopath/fifo2 &
bspc rule -a 'Pcmanfm' desktop='^2'
bspc monitor -d 1 2 3 4 5 6 7 8 9

pidof pcmanfm || pcmanfm &
pidof st || st &
bspc config pointer_modifier mod4
#bspc config pointer_modifier

bspc config border_width         2
bspc config window_gap          5

#bspc config automatic_scheme alternate
#bspc config automatic_scheme longest_side
#bspc config automatic_scheme spiral
#
#ditribucion stack en fibonacci
bspc config automatic_scheme      spiral

bspc config initial_polarity first_child

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config single_monacle       true

bspc config focus_follows_pointer true

bspc config pointer_action1 none
#bspc rule -a firefox-esr desktop='^2'
#bspc rule -a mpv desktop='^4' state=fullscreen follow=on
bspc rule -a mpv state=floating follow=on
#bspc rule -a Zathura desktop='^4' state=fullscreen follow=on
bspc rule -a Firefox-esr desktop='^4' follow=off
bspc rule -a Links desktop='^4' follow=on
bspc rule -a Sxiv state=floating follow=on
#bspc rule -a soffice desktop='^4' follow=on
#bspc rule -a Libreoffice state=floating
#bspc rule -a '*:libreoffice' state=floating desktop='^3' follow=on
#bspc rule -a '*:soffice' state=floating rectangle=480x270+1440+810
#bspc rule -a URxvt:urxvt:'ranger' state=floating
bspc rule -a 'smtube' state=floating rectangle=600x600+400+100 follow=off focus=off
bspc rule -a 'Yad' state=floating rectangle=600x600+400+100 focus=on
bspc rule -a 'Lxappearance' state=floating
bspc rule -a 'Gdebi-gtk' state=floating
bspc rule -a 'Display-im6.q16' state=floating
bspc rule -a 'f-terminal' state=floating
#bspc rule -a firefox:Toolkit state=floating rectangle=600x600+400+100
#bspc rule -a 'Webcam' state=sticky 
#pidof pcmanfm || pcmanfm &
#bspc desktop -f 1
$HOME/.config/bspwm/scripts/bspwm_wks &
#bspc rule -a URxvt::wordgrinder state=floating center=on
#bspc rule -a URxvt::ranger state=floating center=on
#bscp rule -a polybar manage=off
#bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above

#( sleep 2s && bash /usr/local/bin/lemonbar.sh | lemonbar -p -F#FFFFFFFF -B#FF222222 -f "mononoki Nerd Font"-8 -f FontAwesome-8) &
